baseURL = "https://onpointcutlery.com/"
languageCode = "en-us"
title = "On Point Cutlery - Traverse City Knife Sharpening & Mobile Knife Sharpening"
theme = "lomar2021"


[params]
    author = "Andrew M McCall"
    description =  "On Point Cutlery offers expert knife sharpening and tool sharpening services in Traverse City, Michigan.  We come to your business or home and sharpen your knives and tools so they are like new."

[[params.plugins.css]]
  link = "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;1,400;1,600&display=swap"
[[params.plugins.css]]
  link = ""

[markup]
  [markup.goldmark]
     [markup.goldmark.renderer]
      unsafe = true

[menu]

#  [[menu.main]]
#    identifier = "posts"
#    name = "News"
#    pre = "&#8250;"
#    title = "News & Updates"
#    url = "/updates"
#    weight = 7
  [[menu.main]]
    identifier = "about-us"
    name = "About Us"
    pre = "&#8250;"
    title = "About Us"
    url = "/about-us"
    weight = 8
  [[menu.main]]
    identifier = "contact-us"
    name = "Contact Us"
    pre = "&#8250;"
    title = "Contact Us"
    url = "/contact-us"
    weight = 6
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "&#8250;"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Gallery"
    name = "Gallery"
    pre = "&#8250;"
    title = "Gallery"
    url = "/gallery"
    weight = 5
  [[menu.main]]
    identifier = "Services"
    name = "Services"
    pre = "&#8250;"
    title = "Services"
    url = "/services"
    weight = 2
#  [[menu.main]]
#    identifier = "schedule"
#    name = "Book Now"
#    pre = "&#8250;"
#    title = "Schedule"
#    url = "/schedule"
#    weight = 4
  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    pre = "&#8250;"
    title = "Pricing"
    url = "/pricing"
    weight = 3
  [[menu.footer]]
    identifier = "contact-us"
    name = "Contact Us"
    pre = "&#8250;"
    title = "Contact Us"
    url = "/contact-us"
    weight = 2
  [[menu.footer]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    pre = "&#8250;"
    title = "Privacy Policy"
    url = "/privacy-policy"
    weight = 3
  [[menu.footer]]
    identifier = "terms-conditions"
    name = "Terms & Conditions"
    pre = "&#8250;"
    title = "Terms & Conditions"
    url = "/terms-conditions"
    weight = 4
  [[menu.footer]]
    identifier = "home"
    name = "Home"
    pre = "&#8250;"
    title = "Home"
    url = "/"
    weight = 1


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]